### ISSUE TITLE
When mentionList is updated, the pop up is shown automatically

### ISSUE THREAD

**Issue by vishnusbabu** [dmacfarlane/angular-mentions#80] opened 2018-12-12 11:11 UTC
When the mentionList is updated with a new row, the pop up is automatically shown which is not hidden even on a click inside or outside.

**Comment by ujjawalhub** [comment] 2019-04-02 08:08
Hey @vishnusbabu did you find any solution for this... cause I'm facing same issue while handling two mentionList.

**Comment by dmacfarlane** [comment] 2019-04-04 16:10
Can you provide an example, with steps to reproduce the issue?

https://stackblitz.com/edit/angular-mentions

**Comment by dmacfarlane** [comment] 2019-04-16 21:33
Fix committed to master for this issue.

**Closed** 2019-04-26 16:30 UTC

**Comment by dil-aajmera** [comment] 2023-04-13 03:27
this issue still exists, menu opening stays open even after we switch to different tab just because list items are getting updated
