### ISSUE TITLE
angular mentions is not working using chrome 86

### ISSUE THREAD

**Issue by chaouiy** [dmacfarlane/angular-mentions#173] opened 2020-10-08 09:35 UTC
After updaging my chrome browser to `version 86.0.4240.75 (Official Build) (64-bit)` plugin is not working. Nothing happens when I type `@`

**Comment by dmacfarlane** [comment] 2020-10-08 22:47
Duplicate of #174.

**Closed by dmacfarlane** 2020-10-08 22:47 UTC
