### ISSUE TITLE
@mentions menu showing up even after deleting '@' symbol

### ISSUE THREAD

**Issue by saransh944** [dmacfarlane/angular-mentions#59] opened 2017-12-06 22:14 UTC
The menu shows up even after removing '@' symbol (see attached screenshot).
<img width="1023" alt="screen shot 2017-12-06 at 5 08 30 pm" src="https://user-images.githubusercontent.com/29866577/33688272-d97cc04a-daa8-11e7-8dc3-cf7fcbc850f8.png">

**Comment by dmacfarlane** [comment] 2017-12-06 22:20
I'm unable to reproduce. What browser and OS are you using? And what keys are you pressing to get into the state shown in the screenshot?

**Comment by saranshahlawat** [comment] 2017-12-08 02:17
Hi @dmacfarlane,
I'm using Chrome on mac. The way to replicate this issue is:
1. Type nothing but an @ symbol
2. Remove @ symbol
3. Type 'a' (or something else) and then again an 'a' (so two 'a')

**Comment by ascazzola** [comment] 2018-01-04 20:57
I have the same issue, installing from npm. do you know when will launch the fix version?

**Comment by thecoconutstudio** [comment] 2018-11-06 14:53
did anyone solve this?

**Comment by dmacfarlane** [comment] 2018-11-06 15:14
A fix is committed and it will be included in the next release.

**Comment by thecoconutstudio** [comment] 2018-11-06 15:35
Would you be able to point out which commit, so I can include the fix in time being?

**Comment by dmacfarlane** [comment] 2018-11-06 15:57
The original commit is linked above, but there is a different fix (same line) on the config branch which will be the next release. Let me know if these work for you.

**Comment by dmacfarlane** [comment] 2018-11-15 00:35
I just published it for testing, try: npm install angular-mentions@next

**Closed** 2018-12-21 16:19 UTC
Labels: bug
