### ISSUE TITLE
Async search is not working

### ISSUE THREAD

**Issue by vijucalicut** [dmacfarlane/angular-mentions#76] opened 2018-10-15 13:05 UTC
search($event) functionality not working for the given code.
<h3>Minimal Async</h3>
<input [mention]="httpItems | async" (searchTerm)='search($event)' class="form-control" type="text">

**Comment by dmacfarlane** [comment] 2018-10-15 17:45
Duplicate of #60.

**Comment by vijucalicut** [comment] 2018-10-17 06:29
Any fixes for this?

**Comment by dmacfarlane** [comment] 2018-11-01 00:32
This may be fixed on the new config branch if you want to test it there.

**Comment by Fabf** [comment] 2018-11-14 16:13
Can you say when it will be available on NPM?

**Comment by dmacfarlane** [comment] 2018-11-15 00:33
I just published it for testing: `npm install angular-mentions@next`

**Comment by Fabf** [comment] 2018-11-15 08:51
Great I Have tested the update and it seems to work now for async calls! 
Thank you!!

**Closed** 2018-12-21 16:18 UTC
