### ISSUE TITLE
Version 1.4 is throwing this error. This application depends upon a library published using Angular version 14.0.6

### ISSUE THREAD

**Issue by RentCafeDev** [dmacfarlane/angular-mentions#244] opened 2023-05-25 22:34 UTC
We are using Angular-Mentions version 1.4 in our Angular 12 project and getting the error below. According to your release notes version 1.4 is compatible with Angular 12. 

We would greatly appreciate any help resolving this error.

ERROR:
Cannot create property 'message' on string './node_modules/angular-mentions/fesm2020/angular-mentions.mjs: This application depends upon a library published using Angular version 14.0.6, which requires Angular version 14.0.0 or newer to work correctly.

Consider upgrading your application to use a more recent version of Angular.
#19 177.0   427 | }
#19 177.0   428 | MentionListComponent.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "14.0.6", ngImport: i0, type: MentionListComponent, deps: [{ token: i0.ElementRef }], target: i0.ɵɵFactoryTarget.Component });
#19 177.0 > 429 | MentionListComponent.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "14.0.0", version: "14.0.6", type: MentionListComponent, selector: "mention-list", inputs: { labelKey: "labelKey", itemTemplate: "itemTemplate" }, outputs: { itemClick: "itemClick" }, viewQueries: [{ propertyName: "list", first: true, predicate: ["list"], descendants: true, static: true }, { propertyName: "defaultItemTemplate", first: true, predicate: ["defaultItemTemplate"], descendants: true, static: true }], ngImport: i0, template: `

Error: node_modules/angular-mentions/lib/mention-list.component.d.ts:34:18 - error TS2314: Generic type 'ɵɵComponentDeclaration' requires 7 type argument(s).
#19 177.0 
#19 177.0 34     static ɵcmp: i0.ɵɵComponentDeclaration<MentionListComponent, "mention-list", never, { "labelKey": "labelKey"; "itemTemplate": "itemTemplate"; }, { "itemClick": "itemClick"; }, never, never, false>;

Thank you

**Comment by jaimink** [comment] 2023-07-27 21:40
any resolution for this yet?

**Comment by danielraban** [comment] 2023-10-27 12:41
I am using `1.1.3` with angular 12 and it is working, try that.

**Comment by dmacfarlane** [comment] 2024-01-06 19:23
Duplicate of #238.

**Closed by dmacfarlane** 2024-01-06 19:23 UTC
