### ISSUE TITLE
Multiple mention list?

### ISSUE THREAD

**Issue by dessalines** [dmacfarlane/angular-mentions#71] opened 2018-06-12 17:23 UTC
I need to do not just mentions with `@`, but also hashtags with `#`, is there any way to do that with this?

**Comment by dessalines** [comment] 2018-06-14 17:35
`<input type="text" [mention]="[hashTagItems,userItems]" [mentionConfig]="{triggerChar:'[#,@]',maxItems:[10,10],labelKey:['name','tag']}">`

Doesn't work.

**Comment by dmacfarlane** [comment] 2018-08-05 14:52
Duplicate of #22 and #25

**Closed** 2018-11-01 00:30 UTC
